// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminRoleFunctionRel
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public int FunctionId { get; set; }

    public virtual AdminRoleFunction Function { get; set; }

    public virtual AdminRole Role { get; set; }
}