// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminRole
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public int PermissionId { get; set; }

    public int GroupId { get; set; }

    public virtual AdminGroup Group { get; set; }

    public virtual AdminPermission Permission { get; set; }
}