// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminRole
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    // 新增關聯屬性
    public ICollection<AdminUserRoleRel> UserRoles { get; set; } = new List<AdminUserRoleRel>();
}