// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminPermission
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public bool CanManageMembers { get; set; }

    public bool CanManageProducts { get; set; }

    public bool CanManageOrders { get; set; }

    public bool CanManagePromotions { get; set; }

    public bool CanViewReports { get; set; }

    public bool CanConfigureSystem { get; set; }
}