// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminRoleFunction
{
    public int Id { get; set; }

    public string FunctionName { get; set; }

    public virtual ICollection<AdminRoleFunctionRel> AdminRoleFunctionRels { get; set; } = new List<AdminRoleFunctionRel>();
}