// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminUserRoleRel
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    [ForeignKey("User")]
    public int UserId { get; set; }
    [ForeignKey("Role")]
    public int RoleId { get; set; }

    public virtual AdminRole Role { get; set; }

    public virtual AdminUser User { get; set; }
}