// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class AdminGroup
{
    public int Id { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<AdminRole> AdminRoles { get; set; } = new List<AdminRole>();

    public virtual ICollection<AdminUser> AdminUsers { get; set; } = new List<AdminUser>();
}