// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class Category
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public int ParentCategoryId { get; set; }

    public virtual ParentCategory ParentCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}