// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class ParentCategory
{
    public int Id { get; set; }

    public string ParentCategoriesName { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}