// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class Promotion
{
    public int Id { get; set; }

    public string PromotionName { get; set; }

    public int DiscountValue { get; set; }

    public int MinPurchase { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidTo { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}