// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadMe_Back.Models.EFModels;

public partial class User
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public bool IsBanned { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}